#!/bin/bash

# Wrapper script which transparently for the user starts a container, bind
# mounts all the relevant data into it and executes the actual saml_token script.

IMAGE=registry.eu.clara.net/de-systems-tools/aws_saml_token:v1.0.1

SSH_OPTS="\
    -tt \
    -o ForwardAgent=yes \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o ConnectionAttempts=10"


CONTAINER=$(docker run \
    -v ~/.aws:/root/.aws \
    -v ~/.ssh/known_hosts:/known_hosts \
    --tty \
    --rm \
    -d \
    -p 22 \
    "$IMAGE")

PORT=$(docker inspect $CONTAINER --format='{{ (index (index .NetworkSettings.Ports "22/tcp") 0).HostPort }}')
sleep 3
ssh $SSH_OPTS -p $PORT root@localhost /saml_token.py $USER

docker stop $CONTAINER 1>/dev/null &