context:  XXXX

repositories:
  - name: vmware-tanzu
    url: https://vmware-tanzu.github.io/helm-charts


releases:
  # BACKUP
  - name: velero
    namespace: velero
    chart: vmware-tanzu/velero
    version: 2.27.1
    labels:
      group: backup
      app: velero
      release: velero
    values:
      - velero.yaml
