image:
  repository: velero/velero
  tag: v1.7.1
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 500m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 512Mi

initContainers:
  - name: velero-plugin-for-microsoft-azure
    image: velero/velero-plugin-for-microsoft-azure:v1.3.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

podSecurityContext:
  fsGroup: 1337

metrics:
  enabled: false

kubectl:
  image:
    repository: docker.io/bitnami/kubectl

upgradeCRDs: true

configuration:
  provider: azure
  backupStorageLocation:
    name: azure
    bucket: "velero" # CHANGE?
    config:
      resourceGroup = XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      storageAccount= XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  volumeSnapshotLocation:
    name: azure
    config:
      resourceGroup = XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      storageAccount= XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

serviceAccount:
  server:
    create: true
    name: velero
#    annotations:
#      eks.amazonaws.com/role-arn: "arn:aws:iam::384894877891:role/velero-role"

credentials:
  useSecret: true

backupsEnabled: true
snapshotsEnabled: true

deployRestic: false

schedules:
  my-schedule:
    schedule: "30 1 1 1 *"
    template:
      storageLocation: azure
      ttl: "9999h0m0s"
      includedNamespaces:
       - workload
      includedResources:
      - '*'
