image:
  repository: velero/velero
  tag: v1.7.1
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 500m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 512Mi

initContainers:
  - name: velero-plugin-for-gcp
    image: velero/velero-plugin-for-gcp:v1.3.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

metrics:
  enabled: false

kubectl:
  image:
    repository: docker.io/bitnami/kubectl

upgradeCRDs: true
configuration:
  provider: gcp
  backupStorageLocation:
    name: gcp
    bucket: "velero-backups-sergio-test"

credentials:
  useSecret: true

backupsEnabled: true
snapshotsEnabled: true
deployRestic: false

schedules:
  my-schedule:
    schedule: "30 1 1 1 *"
    template:
      storageLocation: gcp
      ttl: "9999h0m0s"
      includedNamespaces:
       - workload
      includedResources:
      - '*'